#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header
#   The name of the custom HTTP header must be X-Served-By
#   The value of the custom HTTP header is the hostname of the server Nginx is running
# Configures new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow request through Port 80
sudo ufw allow 'Nginx HTTP'

# Create an index static page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# code to redirect to YouTube site (Ex. redirect_me to www.youtube.com)
newString="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\tlocation \/ {add_header X-Served-By \$hostname;}"
sudo sed -i "s/server_name _;/$newString/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
newStringTwo="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$newStringTwo/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
