#!/usr/bin/env bash
apt-get -y update
apt-get -y upgrade
apt-get -y install HAproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
listen 70974-lb-01
       bind 0:80
       mode http
       stats enable
       balance roundrobin
       option httpclose
       option forwardfor
       server 70974-web-01 100.26.246.254 check port 80
       server 70974-web-02 54.165.219.197 check port 80
       " | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart


