#!/usr/bin/bash
#nginx permissions

pkill apache2
sed "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
