#!/usr/bin/env bash
# change the user nginx runs on and
# nginx listens to port 8080

sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default

sed -i 's/listen [::]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-available/default

pkill apche2
sudo -u nginx service nginx restart
