#!/usr/bin/env bash
# change the user nginx runs on and
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apche2
sudo -u nginx service nginx restart
